# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-12 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_apply', '0007_auto_20180111_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zjjy_ipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=20, null=True)),
                ('updatetime', models.DateTimeField()),
                ('issuevolplanned', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('publicnewshareplanned', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('issuepriceceiling', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('issuepricefloor', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('tradeunitpriceatceiling', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('issuetype', models.IntegerField(null=True)),
                ('applystartdate', models.DateField(null=True)),
                ('issueenddate', models.DateField(null=True)),
                ('proposedlistdate', models.DateField(null=True)),
                ('datetoaccount', models.DateField(null=True)),
                ('tradeunit', models.IntegerField(null=True)),
                ('marketcode', models.CharField(max_length=10, null=True)),
                ('issueprice', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('pin_yin', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'ZJJY_HK_IPO',
            },
        ),
    ]
