# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-12 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_apply', '0010_zjjy_ipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zjjy_ipo',
        ),
    ]
