# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-17 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_apply', '0012_stock_jy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='jy_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
